package Forms;

import Classes.Auteur;
import Classes.Fonctions;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdel
 */
public class Auteurs extends javax.swing.JFrame {

    Fonctions f = new Fonctions();
    Auteur aut = new Auteur();

    /**
     * Creates new form Genres
     */
    public Auteurs() {
        initComponents();
        f.DisplayIcon(45, 40, null, "/Images/CloseIcon.png", jLabelClose);
        f.DisplayIcon(90, 80, null, "/Images/book.png", jLabelTitre);
        f.DisplayIcon(jLabelVider.getWidth(), jLabelVider.getHeight(), null, "/Images/reset.png", jLabelVider);
        this.setLocationRelativeTo(null);

        f.customTable(jTableAuteurs);
        f.customHeaderTable(jTableAuteurs, new Color(103, 111, 163), 20);

        RemplirComboNat();
        AfficherAuteurs();
        jDateChooserDateNaiss.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNomA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrenomA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSupp = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAuteurs = new javax.swing.JTable();
        jDateChooserDateNaiss = new com.toedter.calendar.JDateChooser();
        jComboBoxNat = new javax.swing.JComboBox<>();
        jLabelError = new javax.swing.JLabel();
        jLabelVider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(205, 222, 255));

        jLabelTitre.setBackground(new java.awt.Color(205, 222, 255));
        jLabelTitre.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(103, 111, 163));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Gestion des auteurs");
        jLabelTitre.setOpaque(true);

        jLabelClose.setBackground(new java.awt.Color(205, 222, 255));
        jLabelClose.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(103, 111, 163));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.setOpaque(true);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("ID :");

        jTextFieldID.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextFieldID.setEnabled(false);

        jTextFieldNomA.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextFieldNomA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNomAMouseClicked(evt);
            }
        });
        jTextFieldNomA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomAActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Nom de auteur :");

        jTextFieldPrenomA.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextFieldPrenomA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPrenomAMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Preom de auteur :");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Date de naissance :");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Nationnalité");

        jButtonSupp.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonSupp.setText("Supprimer");
        jButtonSupp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonAdd.setText("Ajouter");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonMod.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonMod.setText("Modifier");
        jButtonMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jTableAuteurs.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jTableAuteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableAuteurs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableAuteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAuteursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAuteurs);

        jLabelError.setForeground(new java.awt.Color(255, 51, 51));

        jLabelVider.setBackground(new java.awt.Color(255, 255, 255));
        jLabelVider.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelVider.setForeground(new java.awt.Color(103, 111, 163));
        jLabelVider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelVider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldNomA, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(jTextFieldID)
                                    .addComponent(jTextFieldPrenomA, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxNat, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrenomA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxNat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private void jButtonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppActionPerformed
        // TODO add your handling code here:
        try {
            int confirm = JOptionPane.showConfirmDialog(null, "Vous voullez supprime l'auteur");

            if (confirm == JOptionPane.YES_OPTION) {
                int idA = Integer.parseInt(jTextFieldID.getText());

                aut.Supprimer(idA);
                AfficherAuteurs();
            }
            
        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(null, "Auteur n'est pas modifie", "Attention", 2);
        }
    }//GEN-LAST:event_jButtonSuppActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String nomA = jTextFieldNomA.getText();
        String prenomA = jTextFieldPrenomA.getText();

        String dateA = dateFormat.format(jDateChooserDateNaiss.getDate());
        String natA = jComboBoxNat.getSelectedItem().toString();

        if (nomA.isEmpty()) {
            jLabelError.setText("* Entrer le nom d'auteur");
        } else if (prenomA.isEmpty()) {
            jLabelError.setText("* Entrer le prenom d'auteur");
        } else {
            aut.Ajouter(nomA, prenomA, dateA, natA);
            Vider();
            AfficherAuteurs();
            Dashboard.Statistiques();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        String nomA = jTextFieldNomA.getText();
        String prenomA = jTextFieldPrenomA.getText();
        String dateA = dateFormat.format(jDateChooserDateNaiss.getDate());
        String natA = jComboBoxNat.getSelectedItem().toString();

        if (nomA.isEmpty()) {
            jLabelError.setText("* Entrer le nom d'auteur");
        } else if (prenomA.isEmpty()) {
            jLabelError.setText("* Entrer le prenom d'auteur");
        } else {
            try {
                int idA = Integer.parseInt(jTextFieldID.getText());

                aut.Modifier(idA, nomA, prenomA, dateA, natA);
                Vider();
                AfficherAuteurs();

            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, exception.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jTableAuteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAuteursMouseClicked
        try {
            // TODO add your handling code here:
            int index = jTableAuteurs.getSelectedRow();

            String id = jTableAuteurs.getValueAt(index, 0).toString();
            String nom = jTableAuteurs.getValueAt(index, 1).toString();
            String prenom = jTableAuteurs.getValueAt(index, 2).toString();
            String date = jTableAuteurs.getValueAt(index, 3).toString();
            String nat = jTableAuteurs.getValueAt(index, 4).toString();

            jTextFieldID.setText(id);
            jTextFieldNomA.setText(nom);
            jTextFieldPrenomA.setText(prenom);
            Date d = dateFormat.parse(date);
            jDateChooserDateNaiss.setDate(d);
            jComboBoxNat.setSelectedItem(nat);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableAuteursMouseClicked

    private void jTextFieldNomAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNomAMouseClicked
        // TODO add your handling code here:
        jLabelError.setText("");
    }//GEN-LAST:event_jTextFieldNomAMouseClicked

    private void jTextFieldPrenomAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPrenomAMouseClicked
        // TODO add your handling code here:
        jLabelError.setText("");
    }//GEN-LAST:event_jTextFieldPrenomAMouseClicked

    private void jTextFieldNomAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomAActionPerformed

    private void jLabelViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViderMouseClicked
        // TODO add your handling code here:
        Vider();
    }//GEN-LAST:event_jLabelViderMouseClicked

    public void AfficherAuteurs() {
        ArrayList<Auteur> list = aut.Afficher();
        String[] colones = {"ID", "Nom", "Prenom", "Date de naissance", "Nationalité"};

        Object[][] lignes = new Object[list.size()][colones.length];

        for (int i = 0; i < list.size(); i++) {
            lignes[i][0] = list.get(i).getId();
            lignes[i][1] = list.get(i).getNom();
            lignes[i][2] = list.get(i).getPrenom();
            lignes[i][3] = list.get(i).getDateNaiss();
            lignes[i][4] = list.get(i).getNat();
        }

        DefaultTableModel model = new DefaultTableModel(lignes, colones);
        jTableAuteurs.setModel(model);
    }

    public void RemplirComboNat() {
        ArrayList<String> Nationalite = new ArrayList<>(Arrays.asList(
                "Marocaine", "Fidjienne", "Finlandaise", "Française", "Gabonaise", "Gambienne", "Georgienne",
                "Ghaneenne", "Grenadienne", "Guatemalteque", "Guineenne", "Guyanienne", "Haïtienne", "Hellenique",
                "Hondurienne", "Hongroise", "Indienne", "Indonesienne", "Irakienne", "Irlandaise", "Islandaise",
                "Japonaise", "Jordanienne", "Kazakhstanaise", "Kenyane", "Kirghize", "Kiribatienne",
                "Kittitienne-et-nevicienne", "Kossovienne", "Koweitienne", "Laotienne", "Lesothane",
                "Lettone", "Libanaise", "Liberienne", "Libyenne", "Liechtensteinoise", "Lituanienne"));

        for (String s : Nationalite) {
            jComboBoxNat.addItem(s);
        }
    }

    public void Vider() {

        jTextFieldID.setText("");
        jTextFieldNomA.setText("");
        jTextFieldPrenomA.setText("");
        jDateChooserDateNaiss.setDate(new Date());
        jComboBoxNat.setSelectedItem("Marocaine");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Auteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Auteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Auteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Auteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Auteurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonSupp;
    private javax.swing.JComboBox<String> jComboBoxNat;
    private com.toedter.calendar.JDateChooser jDateChooserDateNaiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelVider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAuteurs;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNomA;
    private javax.swing.JTextField jTextFieldPrenomA;
    // End of variables declaration//GEN-END:variables
}
