/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Classes.Fonctions;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.Border;

/**
 *
 * @author abdel
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Fonctions f = new Fonctions();
    Border border1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
    Border border0 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(205,222,255));

    public Dashboard() {
        initComponents();
        f.DisplayIcon(55, 60, null, "/Images/logo_trans.png", jLabelDashLogo);
        this.setLocationRelativeTo(null);
                
        Border borderLeft = BorderFactory.createMatteBorder(0, 0, 0, 1, Color.black);
        jPanelLeft.setBorder(borderLeft);
        
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.yellow);
        jPanelHeader.setBorder(border);
        
        Border borderHeader1 = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(235, 125, 22));
        jPanelStat1_Header.setBorder(borderHeader1);
        
        Border borderHeader2 = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 153, 0));
        jPanelStat2_Header.setBorder(borderHeader2);
        
        Border borderHeader3 = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(115, 40, 125));
        jPanelStat3_Header.setBorder(borderHeader3);
        
        Border borderHeader4 = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(158, 83, 155));
        jPanelStat4_Header.setBorder(borderHeader4);
        
        ButtonHoverEffect();
        addAllBorders();
    }

    public void addAllBorders(){
        Component[] composants = jPanelLeft.getComponents();
        
        for(Component c:composants){
            if(c instanceof JButton){
                JButton button = (JButton) c;
               
                button.setBorder(border0);
            }
        }
    }
    public void ButtonHoverEffect(){
        Component[] composants = jPanelLeft.getComponents();
        
        for(Component c:composants){
            if(c instanceof JButton){
                JButton button = (JButton) c;
                
                button.addMouseListener(new MouseAdapter(){
                    
                    @Override
                    public void mouseEntered(MouseEvent event){
                        button.setBorder(border1);
                    }
                    
                    @Override
                    public void mouseExited(MouseEvent event){
                        button.setBorder(border0);
                    }   
                });
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelDashLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonGes_Genres = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonGesAut = new javax.swing.JButton();
        jButtonAj = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonMod = new javax.swing.JButton();
        jButtonSupp = new javax.swing.JButton();
        jButtonListeAdhr = new javax.swing.JButton();
        jPanel_Stat_1 = new javax.swing.JPanel();
        jPanelStat1_Header = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_Stat_2 = new javax.swing.JPanel();
        jPanelStat2_Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel_Stat_3 = new javax.swing.JPanel();
        jPanelStat3_Header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel_Stat_4 = new javax.swing.JPanel();
        jPanelStat4_Header = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelLeft.setBackground(new java.awt.Color(205, 222, 255));

        jPanelHeader.setBackground(new java.awt.Color(103, 111, 163));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bibliothèque");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDashLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDashLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelDashLogo.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Genres");

        jButtonGes_Genres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonGes_Genres.setText("Gestion genres");
        jButtonGes_Genres.setContentAreaFilled(false);
        jButtonGes_Genres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGes_Genres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGes_GenresActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Auteurs");

        jButtonGesAut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonGesAut.setText("Gestion auteurs");
        jButtonGesAut.setContentAreaFilled(false);
        jButtonGesAut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGesAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesAutActionPerformed(evt);
            }
        });

        jButtonAj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAj.setText("Ajouter nouveau");
        jButtonAj.setContentAreaFilled(false);
        jButtonAj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Adherent");

        jButtonMod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonMod.setText("Modifier nouveau");
        jButtonMod.setContentAreaFilled(false);
        jButtonMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonSupp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSupp.setText("Supprimer nouveau");
        jButtonSupp.setContentAreaFilled(false);
        jButtonSupp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppActionPerformed(evt);
            }
        });

        jButtonListeAdhr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonListeAdhr.setText("Liste des adherents");
        jButtonListeAdhr.setContentAreaFilled(false);
        jButtonListeAdhr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListeAdhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeAdhrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(107, 107, 107))
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGes_Genres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGesAut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(107, 107, 107))
                    .addComponent(jButtonSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListeAdhr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGes_Genres)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGesAut)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListeAdhr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_Stat_1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel_Stat_1.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat1_Header.setBackground(new java.awt.Color(255, 51, 0));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ouvrages");

        javax.swing.GroupLayout jPanelStat1_HeaderLayout = new javax.swing.GroupLayout(jPanelStat1_Header);
        jPanelStat1_Header.setLayout(jPanelStat1_HeaderLayout);
        jPanelStat1_HeaderLayout.setHorizontalGroup(
            jPanelStat1_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat1_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanelStat1_HeaderLayout.setVerticalGroup(
            jPanelStat1_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStat1_HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("12426");

        javax.swing.GroupLayout jPanel_Stat_1Layout = new javax.swing.GroupLayout(jPanel_Stat_1);
        jPanel_Stat_1.setLayout(jPanel_Stat_1Layout);
        jPanel_Stat_1Layout.setHorizontalGroup(
            jPanel_Stat_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat1_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_Stat_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Stat_1Layout.setVerticalGroup(
            jPanel_Stat_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_1Layout.createSequentialGroup()
                .addComponent(jPanelStat1_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        jPanel_Stat_2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_Stat_2.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat2_Header.setBackground(new java.awt.Color(0, 255, 102));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adhérents");

        javax.swing.GroupLayout jPanelStat2_HeaderLayout = new javax.swing.GroupLayout(jPanelStat2_Header);
        jPanelStat2_Header.setLayout(jPanelStat2_HeaderLayout);
        jPanelStat2_HeaderLayout.setHorizontalGroup(
            jPanelStat2_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat2_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanelStat2_HeaderLayout.setVerticalGroup(
            jPanelStat2_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStat2_HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("124");

        javax.swing.GroupLayout jPanel_Stat_2Layout = new javax.swing.GroupLayout(jPanel_Stat_2);
        jPanel_Stat_2.setLayout(jPanel_Stat_2Layout);
        jPanel_Stat_2Layout.setHorizontalGroup(
            jPanel_Stat_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat2_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Stat_2Layout.setVerticalGroup(
            jPanel_Stat_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_2Layout.createSequentialGroup()
                .addComponent(jPanelStat2_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel_Stat_3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel_Stat_3.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat3_Header.setBackground(new java.awt.Color(0, 0, 204));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Auteurs");

        javax.swing.GroupLayout jPanelStat3_HeaderLayout = new javax.swing.GroupLayout(jPanelStat3_Header);
        jPanelStat3_Header.setLayout(jPanelStat3_HeaderLayout);
        jPanelStat3_HeaderLayout.setHorizontalGroup(
            jPanelStat3_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat3_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanelStat3_HeaderLayout.setVerticalGroup(
            jPanelStat3_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat3_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(102, 102, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("14");

        javax.swing.GroupLayout jPanel_Stat_3Layout = new javax.swing.GroupLayout(jPanel_Stat_3);
        jPanel_Stat_3.setLayout(jPanel_Stat_3Layout);
        jPanel_Stat_3Layout.setHorizontalGroup(
            jPanel_Stat_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat3_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Stat_3Layout.setVerticalGroup(
            jPanel_Stat_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_3Layout.createSequentialGroup()
                .addComponent(jPanelStat3_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        jPanel_Stat_4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel_Stat_4.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat4_Header.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanelStat4_HeaderLayout = new javax.swing.GroupLayout(jPanelStat4_Header);
        jPanelStat4_Header.setLayout(jPanelStat4_HeaderLayout);
        jPanelStat4_HeaderLayout.setHorizontalGroup(
            jPanelStat4_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelStat4_HeaderLayout.setVerticalGroup(
            jPanelStat4_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_Stat_4Layout = new javax.swing.GroupLayout(jPanel_Stat_4);
        jPanel_Stat_4.setLayout(jPanel_Stat_4Layout);
        jPanel_Stat_4Layout.setHorizontalGroup(
            jPanel_Stat_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat4_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Stat_4Layout.setVerticalGroup(
            jPanel_Stat_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_4Layout.createSequentialGroup()
                .addComponent(jPanelStat4_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jPanel_Stat_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel_Stat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jPanel_Stat_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Stat_4, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Stat_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Stat_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Stat_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jPanel_Stat_4, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGes_GenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGes_GenresActionPerformed
        // TODO add your handling code here:
        Genres g = new Genres();
        g.setVisible(true);
    }//GEN-LAST:event_jButtonGes_GenresActionPerformed

    private void jButtonGesAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesAutActionPerformed
        // TODO add your handling code here:
        Auteurs a = new Auteurs();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonGesAutActionPerformed

    private void jButtonAjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjActionPerformed
        // TODO add your handling code here:
        AjouterAdherent aj = new AjouterAdherent();
        aj.setVisible(true);
    }//GEN-LAST:event_jButtonAjActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        ModifierAdherent mod = new ModifierAdherent();
        mod.setVisible(true);
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppActionPerformed
        // TODO add your handling code here:
        ModifierAdherent supp = new ModifierAdherent();
        supp.setVisible(true);
    }//GEN-LAST:event_jButtonSuppActionPerformed

    private void jButtonListeAdhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeAdhrActionPerformed
        // TODO add your handling code here:
        ListeAdherents la = new ListeAdherents();
        la.setVisible(true);
    }//GEN-LAST:event_jButtonListeAdhrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAj;
    private javax.swing.JButton jButtonGesAut;
    private javax.swing.JButton jButtonGes_Genres;
    private javax.swing.JButton jButtonListeAdhr;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonSupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDashLogo;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelStat1_Header;
    private javax.swing.JPanel jPanelStat2_Header;
    private javax.swing.JPanel jPanelStat3_Header;
    private javax.swing.JPanel jPanelStat4_Header;
    private javax.swing.JPanel jPanel_Stat_1;
    private javax.swing.JPanel jPanel_Stat_2;
    private javax.swing.JPanel jPanel_Stat_3;
    private javax.swing.JPanel jPanel_Stat_4;
    // End of variables declaration//GEN-END:variables
}
