/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Classes.Fonctions;
import Classes.Livre;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author abdel
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    Fonctions f = new Fonctions();
    Border border1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.ORANGE);
    Border border0 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(205, 222, 255));
    Livre livre = new Livre();

    public static void Statistiques() {
        jLabelOuv.setText(Fonctions.countData("livre") + "");
        jLabelAdh.setText(Fonctions.countData("adherent") + "");
        jLabelAut.setText(Fonctions.countData("auteur") + "");
    }

    private void Borders() {
        Border borderLeft = BorderFactory.createMatteBorder(0, 0, 0, 1, Color.black);
        jPanelLeft.setBorder(borderLeft);

        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.yellow);
        jPanelHeader.setBorder(border);

        Border borderHeader1 = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(235, 125, 22));
        jPanelStat1_Header.setBorder(borderHeader1);

        Border borderHeader2 = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 153, 0));
        jPanelStat2_Header.setBorder(borderHeader2);

        Border borderHeader3 = BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(115, 40, 125));
        jPanelStat3_Header.setBorder(borderHeader3);

        Border borderHeader4 = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(158, 83, 155));
        jPanelStat4_Header.setBorder(borderHeader4);
    }

    public Dashboard() {
        initComponents();
        f.DisplayIcon(55, 60, null, "/Images/logo_trans.png", jLabelDashLogo);
        f.DisplayIcon(jLabelAcc.getWidth(), jLabelAcc.getHeight(), null, "/Images/refresh.png", jLabelAcc);
        this.setLocationRelativeTo(null);

        Borders();
        ButtonHoverEffect();
        addAllBorders();
        Statistiques();

        JLabel[] jLabels = new JLabel[4];

        jLabels[0] = jLabelImg1;
        jLabels[1] = jLabelImg2;
        jLabels[2] = jLabelImg3;
        jLabels[3] = jLabelImg4;

        livre.DisplayLivreCover(jLabels);
    }

    private void addAllBorders() {
        Component[] composants = jPanelLeft.getComponents();

        for (Component c : composants) {
            if (c instanceof JButton) {
                JButton button = (JButton) c;

                button.setBorder(border0);
            }
        }
    }

    private void ButtonHoverEffect() {
        Component[] composants = jPanelLeft.getComponents();

        for (Component c : composants) {
            if (c instanceof JButton) {
                JButton button = (JButton) c;

                button.addMouseListener(new MouseAdapter() {

                    @Override
                    public void mouseEntered(MouseEvent event) {
                        button.setBorder(border1);
                    }

                    @Override
                    public void mouseExited(MouseEvent event) {
                        button.setBorder(border0);
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelDashLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelLv = new javax.swing.JLabel();
        jLabelLv1 = new javax.swing.JLabel();
        jLabelQuiter = new javax.swing.JLabel();
        jButtonGes_Genres = new javax.swing.JButton();
        jButtonGesAut = new javax.swing.JButton();
        jButtonAjAdh = new javax.swing.JButton();
        jButtonModAdh = new javax.swing.JButton();
        jButtonListeAdhr = new javax.swing.JButton();
        jButtonAjLv = new javax.swing.JButton();
        jButtonModLv = new javax.swing.JButton();
        jButtonListeLvs = new javax.swing.JButton();
        jButtonRLv = new javax.swing.JButton();
        jButtonGesEmp = new javax.swing.JButton();
        jPanel_Stat_1 = new javax.swing.JPanel();
        jPanelStat1_Header = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelOuv = new javax.swing.JLabel();
        jPanel_Stat_2 = new javax.swing.JPanel();
        jPanelStat2_Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAdh = new javax.swing.JLabel();
        jPanel_Stat_3 = new javax.swing.JPanel();
        jPanelStat3_Header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelAut = new javax.swing.JLabel();
        jPanel_Stat_4 = new javax.swing.JPanel();
        jPanelStat4_Header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelAcc = new javax.swing.JLabel();
        jLabelImg1 = new javax.swing.JLabel();
        jLabelImg2 = new javax.swing.JLabel();
        jLabelImg3 = new javax.swing.JLabel();
        jLabelImg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanelHome.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelLeft.setBackground(new java.awt.Color(205, 222, 255));

        jPanelHeader.setBackground(new java.awt.Color(103, 111, 163));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bibliothèque");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDashLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jLabelDashLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelDashLogo.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thémes");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Auteurs");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Adherent");

        jLabelLv.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelLv.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLv.setText("Livres");

        jLabelLv1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelLv1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLv1.setText("Emprunt");

        jLabelQuiter.setBackground(java.awt.Color.red);
        jLabelQuiter.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelQuiter.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuiter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuiter.setText("Déconnecter");
        jLabelQuiter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelQuiter.setOpaque(true);
        jLabelQuiter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelQuiterMouseClicked(evt);
            }
        });

        jButtonGes_Genres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGes_Genres.setText("Gestion thémes");
        jButtonGes_Genres.setContentAreaFilled(false);
        jButtonGes_Genres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGes_Genres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGes_GenresActionPerformed(evt);
            }
        });

        jButtonGesAut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGesAut.setText("Gestion auteurs");
        jButtonGesAut.setContentAreaFilled(false);
        jButtonGesAut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGesAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesAutActionPerformed(evt);
            }
        });

        jButtonAjAdh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAjAdh.setText("Ajouter");
        jButtonAjAdh.setContentAreaFilled(false);
        jButtonAjAdh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAjAdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjAdhActionPerformed(evt);
            }
        });

        jButtonModAdh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonModAdh.setText("Modifier ou Supprimer");
        jButtonModAdh.setContentAreaFilled(false);
        jButtonModAdh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModAdh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModAdhActionPerformed(evt);
            }
        });

        jButtonListeAdhr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListeAdhr.setText("Liste des adherents");
        jButtonListeAdhr.setContentAreaFilled(false);
        jButtonListeAdhr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListeAdhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeAdhrActionPerformed(evt);
            }
        });

        jButtonAjLv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAjLv.setText("Ajouter");
        jButtonAjLv.setContentAreaFilled(false);
        jButtonAjLv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAjLv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjLvActionPerformed(evt);
            }
        });

        jButtonModLv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonModLv.setText("Modifier ou Supprimer");
        jButtonModLv.setContentAreaFilled(false);
        jButtonModLv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModLv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModLvActionPerformed(evt);
            }
        });

        jButtonListeLvs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonListeLvs.setText("Liste des livres");
        jButtonListeLvs.setContentAreaFilled(false);
        jButtonListeLvs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListeLvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeLvsActionPerformed(evt);
            }
        });

        jButtonRLv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRLv.setText("Rendue livre");
        jButtonRLv.setContentAreaFilled(false);
        jButtonRLv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRLv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRLvActionPerformed(evt);
            }
        });

        jButtonGesEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGesEmp.setText("Gestion emprunts");
        jButtonGesEmp.setContentAreaFilled(false);
        jButtonGesEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGesEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGesEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabelLv))
                        .addGap(119, 119, 119))
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGes_Genres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGesAut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAjAdh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModAdh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListeLvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListeAdhr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAjLv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonModLv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGesEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelLv1))
                            .addComponent(jButtonRLv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jLabelQuiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGes_Genres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGesAut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAjAdh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModAdh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListeAdhr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAjLv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModLv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListeLvs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRLv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGesEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelQuiter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Stat_1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel_Stat_1.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat1_Header.setBackground(new java.awt.Color(255, 51, 0));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ouvrages");

        javax.swing.GroupLayout jPanelStat1_HeaderLayout = new javax.swing.GroupLayout(jPanelStat1_Header);
        jPanelStat1_Header.setLayout(jPanelStat1_HeaderLayout);
        jPanelStat1_HeaderLayout.setHorizontalGroup(
            jPanelStat1_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat1_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanelStat1_HeaderLayout.setVerticalGroup(
            jPanelStat1_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStat1_HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelOuv.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabelOuv.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOuv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOuv.setText("12426");

        javax.swing.GroupLayout jPanel_Stat_1Layout = new javax.swing.GroupLayout(jPanel_Stat_1);
        jPanel_Stat_1.setLayout(jPanel_Stat_1Layout);
        jPanel_Stat_1Layout.setHorizontalGroup(
            jPanel_Stat_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat1_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_Stat_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOuv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Stat_1Layout.setVerticalGroup(
            jPanel_Stat_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_1Layout.createSequentialGroup()
                .addComponent(jPanelStat1_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelOuv, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        jPanel_Stat_2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel_Stat_2.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat2_Header.setBackground(new java.awt.Color(0, 255, 102));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adhérents");

        javax.swing.GroupLayout jPanelStat2_HeaderLayout = new javax.swing.GroupLayout(jPanelStat2_Header);
        jPanelStat2_Header.setLayout(jPanelStat2_HeaderLayout);
        jPanelStat2_HeaderLayout.setHorizontalGroup(
            jPanelStat2_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat2_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanelStat2_HeaderLayout.setVerticalGroup(
            jPanelStat2_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStat2_HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelAdh.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabelAdh.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdh.setText("124");

        javax.swing.GroupLayout jPanel_Stat_2Layout = new javax.swing.GroupLayout(jPanel_Stat_2);
        jPanel_Stat_2.setLayout(jPanel_Stat_2Layout);
        jPanel_Stat_2Layout.setHorizontalGroup(
            jPanel_Stat_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat2_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelAdh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Stat_2Layout.setVerticalGroup(
            jPanel_Stat_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_2Layout.createSequentialGroup()
                .addComponent(jPanelStat2_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelAdh)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel_Stat_3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel_Stat_3.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat3_Header.setBackground(new java.awt.Color(0, 0, 204));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Auteurs");

        javax.swing.GroupLayout jPanelStat3_HeaderLayout = new javax.swing.GroupLayout(jPanelStat3_Header);
        jPanelStat3_Header.setLayout(jPanelStat3_HeaderLayout);
        jPanelStat3_HeaderLayout.setHorizontalGroup(
            jPanelStat3_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat3_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(110, 110, 110))
        );
        jPanelStat3_HeaderLayout.setVerticalGroup(
            jPanelStat3_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat3_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelAut.setBackground(new java.awt.Color(102, 102, 255));
        jLabelAut.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabelAut.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAut.setText("14");

        javax.swing.GroupLayout jPanel_Stat_3Layout = new javax.swing.GroupLayout(jPanel_Stat_3);
        jPanel_Stat_3.setLayout(jPanel_Stat_3Layout);
        jPanel_Stat_3Layout.setHorizontalGroup(
            jPanel_Stat_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat3_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelAut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Stat_3Layout.setVerticalGroup(
            jPanel_Stat_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_3Layout.createSequentialGroup()
                .addComponent(jPanelStat3_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabelAut)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        jPanel_Stat_4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel_Stat_4.setPreferredSize(new java.awt.Dimension(250, 200));

        jPanelStat4_Header.setBackground(new java.awt.Color(255, 102, 102));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Les derniers livres qui on a ajouter");

        jLabelAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelStat4_HeaderLayout = new javax.swing.GroupLayout(jPanelStat4_Header);
        jPanelStat4_Header.setLayout(jPanelStat4_HeaderLayout);
        jPanelStat4_HeaderLayout.setHorizontalGroup(
            jPanelStat4_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat4_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelStat4_HeaderLayout.setVerticalGroup(
            jPanelStat4_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStat4_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStat4_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStat4_HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelImg1.setBackground(new java.awt.Color(153, 204, 255));
        jLabelImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImg1.setName("jLabelImg1"); // NOI18N
        jLabelImg1.setOpaque(true);

        jLabelImg2.setBackground(new java.awt.Color(153, 204, 255));
        jLabelImg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImg2.setName("jLabelImg2"); // NOI18N
        jLabelImg2.setOpaque(true);

        jLabelImg3.setBackground(new java.awt.Color(153, 204, 255));
        jLabelImg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImg3.setName("jLabelImg3"); // NOI18N
        jLabelImg3.setOpaque(true);

        jLabelImg4.setBackground(new java.awt.Color(153, 204, 255));
        jLabelImg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelImg4.setName("jLabelImg4"); // NOI18N
        jLabelImg4.setOpaque(true);

        javax.swing.GroupLayout jPanel_Stat_4Layout = new javax.swing.GroupLayout(jPanel_Stat_4);
        jPanel_Stat_4.setLayout(jPanel_Stat_4Layout);
        jPanel_Stat_4Layout.setHorizontalGroup(
            jPanel_Stat_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStat4_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Stat_4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel_Stat_4Layout.setVerticalGroup(
            jPanel_Stat_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Stat_4Layout.createSequentialGroup()
                .addComponent(jPanelStat4_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Stat_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelImg3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(jLabelImg2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImg1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelImg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jPanel_Stat_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel_Stat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jPanel_Stat_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Stat_4, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Stat_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Stat_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Stat_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Stat_4, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGes_GenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGes_GenresActionPerformed
        // TODO add your handling code here:
        Genres g = new Genres();
        g.setVisible(true);
    }//GEN-LAST:event_jButtonGes_GenresActionPerformed

    private void jButtonGesAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesAutActionPerformed
        // TODO add your handling code here:
        Auteurs a = new Auteurs();
        a.setVisible(true);
    }//GEN-LAST:event_jButtonGesAutActionPerformed

    private void jButtonAjAdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjAdhActionPerformed
        // TODO add your handling code here:
        AjouterAdherent aj = new AjouterAdherent();
        aj.setVisible(true);
    }//GEN-LAST:event_jButtonAjAdhActionPerformed

    private void jButtonModAdhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModAdhActionPerformed
        // TODO add your handling code here:
        ModifierAdherent mod = new ModifierAdherent();
        mod.setVisible(true);
    }//GEN-LAST:event_jButtonModAdhActionPerformed

    private void jButtonListeAdhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeAdhrActionPerformed
        // TODO add your handling code here:
        ListeAdherents la = new ListeAdherents();
        la.setVisible(true);
    }//GEN-LAST:event_jButtonListeAdhrActionPerformed

    private void jButtonAjLvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjLvActionPerformed
        // TODO add your handling code here:
        AjouterLivre ajouterLivre = new AjouterLivre();
        ajouterLivre.setVisible(true);
    }//GEN-LAST:event_jButtonAjLvActionPerformed

    private void jButtonModLvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModLvActionPerformed
        // TODO add your handling code here:
        ModifierLivre modifierLivre = new ModifierLivre();
        modifierLivre.setVisible(true);
    }//GEN-LAST:event_jButtonModLvActionPerformed

    private void jButtonListeLvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeLvsActionPerformed
        // TODO add your handling code here:
        ListeLivres livres = new ListeLivres();
        livres.setVisible(true);
    }//GEN-LAST:event_jButtonListeLvsActionPerformed

    private void jButtonRLvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRLvActionPerformed
        // TODO add your handling code here:
        EmpruntLivre empruntLivre = new EmpruntLivre();
        empruntLivre.setVisible(true);
    }//GEN-LAST:event_jButtonRLvActionPerformed

    private void jButtonGesEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGesEmpActionPerformed
        // TODO add your handling code here:
        RetourLivre retourLivre = new RetourLivre();
        retourLivre.setVisible(true);
    }//GEN-LAST:event_jButtonGesEmpActionPerformed

    private void jLabelQuiterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelQuiterMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jLabelQuiterMouseClicked

    private void jLabelAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Dashboard d = new Dashboard();
        d.setVisible(true);
    }//GEN-LAST:event_jLabelAccMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjAdh;
    private javax.swing.JButton jButtonAjLv;
    private javax.swing.JButton jButtonGesAut;
    private javax.swing.JButton jButtonGesEmp;
    private javax.swing.JButton jButtonGes_Genres;
    private javax.swing.JButton jButtonListeAdhr;
    private javax.swing.JButton jButtonListeLvs;
    private javax.swing.JButton jButtonModAdh;
    private javax.swing.JButton jButtonModLv;
    private javax.swing.JButton jButtonRLv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAcc;
    public static javax.swing.JLabel jLabelAdh;
    public static javax.swing.JLabel jLabelAut;
    private javax.swing.JLabel jLabelDashLogo;
    private javax.swing.JLabel jLabelImg1;
    private javax.swing.JLabel jLabelImg2;
    private javax.swing.JLabel jLabelImg3;
    private javax.swing.JLabel jLabelImg4;
    private javax.swing.JLabel jLabelLv;
    private javax.swing.JLabel jLabelLv1;
    public static javax.swing.JLabel jLabelOuv;
    private javax.swing.JLabel jLabelQuiter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelStat1_Header;
    private javax.swing.JPanel jPanelStat2_Header;
    private javax.swing.JPanel jPanelStat3_Header;
    private javax.swing.JPanel jPanelStat4_Header;
    private javax.swing.JPanel jPanel_Stat_1;
    private javax.swing.JPanel jPanel_Stat_2;
    private javax.swing.JPanel jPanel_Stat_3;
    private javax.swing.JPanel jPanel_Stat_4;
    // End of variables declaration//GEN-END:variables
}
