package Forms;

import Classes.Adherent;
import Classes.Emprunter;
import Classes.Fonctions;
import Classes.Livre;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abdel
 */
public class RetourLivre extends javax.swing.JFrame {

    Fonctions f = new Fonctions();
    Emprunter emprunter = new Emprunter();
    Livre l = new Livre();
    Adherent a = new Adherent();
    
    /**
     * Creates new form Genres
     */
    public RetourLivre() {

        initComponents();
        f.DisplayIcon(45, 40, null, "/Images/CloseIcon.png", jLabelClose);
        f.DisplayIcon(90, 80, null, "/Images/book.png", jLabelTitre);
        this.setLocationRelativeTo(null);

        f.customTable(jTableEmpLivres);
        f.customHeaderTable(jTableEmpLivres, new Color(103, 111, 163), 20);

        AfficherLivreEmp("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpLivres = new javax.swing.JTable();
        jSpinnerLvID = new javax.swing.JSpinner();
        jSpinnerAdhID = new javax.swing.JSpinner();
        jLabelLvInfo = new javax.swing.JLabel();
        jLabelAdhInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooserDateEmp = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooserDateRetour = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObser = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButtonRet = new javax.swing.JButton();
        jButtonPerdu = new javax.swing.JButton();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonSupp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(205, 222, 255));

        jLabelTitre.setBackground(new java.awt.Color(205, 222, 255));
        jLabelTitre.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelTitre.setForeground(new java.awt.Color(103, 111, 163));
        jLabelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitre.setText("Retour livre");
        jLabelTitre.setOpaque(true);

        jLabelClose.setBackground(new java.awt.Color(205, 222, 255));
        jLabelClose.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(103, 111, 163));
        jLabelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.setOpaque(true);
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableEmpLivres.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jTableEmpLivres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEmpLivres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableEmpLivres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpLivresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpLivres);

        jSpinnerLvID.setEnabled(false);

        jSpinnerAdhID.setEnabled(false);

        jLabelLvInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelLvInfo.setForeground(new java.awt.Color(51, 51, 255));
        jLabelLvInfo.setText("Livre informations");
        jLabelLvInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLvInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLvInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLvInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLvInfoMouseExited(evt);
            }
        });

        jLabelAdhInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelAdhInfo.setForeground(new java.awt.Color(51, 51, 255));
        jLabelAdhInfo.setText("Adherent informations");
        jLabelAdhInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAdhInfo.setDoubleBuffered(true);
        jLabelAdhInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdhInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAdhInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAdhInfoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Sélectionner l'id de l'adherent :");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Sélectionner l'id de livre  :");

        jDateChooserDateEmp.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("Date d'émission :");

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel11.setText("Date de retour :");

        jTextAreaObser.setColumns(20);
        jTextAreaObser.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jTextAreaObser.setRows(5);
        jScrollPane2.setViewportView(jTextAreaObser);

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("Observation :");

        jButtonRet.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonRet.setText("Retourne");
        jButtonRet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetActionPerformed(evt);
            }
        });

        jButtonPerdu.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonPerdu.setText("Perdu");
        jButtonPerdu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPerdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerduActionPerformed(evt);
            }
        });

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tout", "Rendue", "Retourne", "Perdu" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Selectioner livre satut  :");

        jButtonSupp.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonSupp.setText("Supprimer");
        jButtonSupp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDateChooserDateRetour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerLvID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLvInfo)
                                    .addComponent(jLabelAdhInfo)))
                            .addComponent(jSpinnerAdhID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDateEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRet, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPerdu, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jSpinnerLvID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLvInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jSpinnerAdhID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAdhInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserDateEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserDateRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRet, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPerdu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jTableEmpLivresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpLivresMouseClicked
        try {
            // TODO add your handling code here:
            int index = jTableEmpLivres.getSelectedRow();

            int idLv = Integer.parseInt(jTableEmpLivres.getValueAt(index, 1).toString());
            
            Livre livre = l.getLivreById(idLv, null);
            jLabelLvInfo.setText(livre.getTitre());
            
            int idAdh = Integer.parseInt(jTableEmpLivres.getValueAt(index, 2).toString());
            
            Adherent adherent = a.getAdherentById(null, idAdh);
            jLabelAdhInfo.setText(adherent.getNom()+" "+adherent.getPrenom());
            
            String dateE = jTableEmpLivres.getValueAt(index, 3).toString();
            String dateR = jTableEmpLivres.getValueAt(index, 4).toString();
            String statut = jTableEmpLivres.getValueAt(index, 5).toString();
            String obser = jTableEmpLivres.getValueAt(index, 6).toString();

            jSpinnerLvID.setValue(idLv);
            jSpinnerAdhID.setValue(idAdh);

            java.util.Date dE = new SimpleDateFormat("yyyy-MM-dd").parse(dateE);
            java.util.Date dR = new SimpleDateFormat("yyyy-MM-dd").parse(dateR);
            jDateChooserDateEmp.setDate(dE);
            jDateChooserDateRetour.setDate(dR);

            jTextAreaObser.setText(obser);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTableEmpLivresMouseClicked

    private void jButtonRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:            
            int idLv = (int) jSpinnerLvID.getValue();
            int idAdh = (int) jSpinnerAdhID.getValue();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateE = dateFormat.format(jDateChooserDateEmp.getDate());
            String dateR = dateFormat.format(jDateChooserDateRetour.getDate());

            Date dE = dateFormat.parse(dateE);
            Date dR = dateFormat.parse(dateR);

            if (dE != null || dR != null) {
                int index = jTableEmpLivres.getSelectedRow();
                int idEmp = 0;

                String obser = jTextAreaObser.getText();

                if (dR.before(dE)) {

                    JOptionPane.showMessageDialog(null, "La date de retour doit apres la date d'emprunt !!!!", "Attention", 2);
                } else if (index == -1) {
                    JOptionPane.showMessageDialog(null, "Vous pouvez selectionne d'abord un ligne !!!!", "Attention", 2);
                } else {
                    idEmp = Integer.parseInt(jTableEmpLivres.getValueAt(index, 0).toString());
                    emprunter.Modifier(idEmp, idLv, idAdh, "Retourne", dateE, dateR, obser);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vous pouvez selectionne d'abord un ligne !!!!", "Attention", 2);
            }

        } catch (ParseException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Vous pouvez selectionne d'abord un ligne !!!!", "Attention", 2);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRetActionPerformed

    private void jButtonPerduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerduActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:            
            int idLv = (int) jSpinnerLvID.getValue();
            int idAdh = (int) jSpinnerAdhID.getValue();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateE = dateFormat.format(jDateChooserDateEmp.getDate());
            String dateR = dateFormat.format(jDateChooserDateRetour.getDate());

            Date dE = dateFormat.parse(dateE);
            Date dR = dateFormat.parse(dateR);

            if (dE != null || dR != null) {
                int index = jTableEmpLivres.getSelectedRow();
                int idEmp = 0;

                String obser = jTextAreaObser.getText();

                if (dR.before(dE)) {

                    JOptionPane.showMessageDialog(null, "La date de retour doit apres la date d'emprunt !!!!", "Attention", 2);
                } else if (index == -1) {
                    JOptionPane.showMessageDialog(null, "Vous pouvez selectionne d'abord un ligne !!!!", "Attention", 2);
                } else {
                    idEmp = Integer.parseInt(jTableEmpLivres.getValueAt(index, 0).toString());
                    emprunter.Modifier(idEmp, idLv, idAdh, "Perdu", dateE, dateR, obser);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vous pouvez selectionne d'abord un ligne !!!!", "Attention", 2);
            }

        } catch (ParseException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Vous pouvez selectionne d'abord un ligne !!!!", "Attention", 2);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPerduActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
        String statut = jComboBoxStatus.getSelectedItem().toString();

        if (statut.equals("Tout")) {
            statut = "";
        }

        AfficherLivreEmp(statut);
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jButtonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuppActionPerformed
        // TODO add your handling code here:
        try {

            int index = jTableEmpLivres.getSelectedRow();

            int confirm = JOptionPane.showConfirmDialog(null, "Vous voullez supprime ce emprunt d'un livre");

            if (confirm == JOptionPane.YES_OPTION && index != -1) {
                int idEmp = Integer.parseInt(jTableEmpLivres.getValueAt(index, 0).toString());

                emprunter.Supprimer(idEmp);
                AfficherLivreEmp("");
            } else {
                JOptionPane.showMessageDialog(null, "Emprunt livre n'est pas supprime", "Attention", 2);
            }

        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(null, "Emprunt livre n'est pas supprime", "Attention", 2);
        }
    }//GEN-LAST:event_jButtonSuppActionPerformed

    public static String typeInfo = "";
    public static int idLv;
    public static int idAdhr;
    private void jLabelLvInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLvInfoMouseClicked
        // TODO add your handling code here:
        typeInfo = "LivreR";

        idLv = (int) jSpinnerLvID.getValue();

        if (jLabelLvInfo.getText().equals("Livre informations")) {

            JOptionPane.showMessageDialog(null, "Le livre que vous recherche n'existe pas", "Attention", 2);
        } else {
            Informations i = new Informations();
            i.setVisible(true);
        }
    }//GEN-LAST:event_jLabelLvInfoMouseClicked

    private void jLabelAdhInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdhInfoMouseClicked
        // TODO add your handling code here:
        typeInfo = "AdherentR";
        idAdhr = (int) jSpinnerAdhID.getValue();

        if (jLabelAdhInfo.getText().equals("Adherent informations")) {

            JOptionPane.showMessageDialog(null, "L'adherent que vous recherche n'existe pas", "Attention", 2);
        } else {
            Informations i = new Informations();
            i.setVisible(true);
        }
    }//GEN-LAST:event_jLabelAdhInfoMouseClicked

    private void jLabelLvInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLvInfoMouseEntered
        // TODO add your handling code here:
        f.setBorderToJLabel(new Color(51, 51, 255), jLabelLvInfo);
    }//GEN-LAST:event_jLabelLvInfoMouseEntered

    private void jLabelLvInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLvInfoMouseExited
        // TODO add your handling code here:
        f.setBorderToJLabel(Color.WHITE, jLabelLvInfo);
    }//GEN-LAST:event_jLabelLvInfoMouseExited

    private void jLabelAdhInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdhInfoMouseEntered
        // TODO add your handling code here:
        f.setBorderToJLabel(new Color(51, 51, 255), jLabelAdhInfo);
    }//GEN-LAST:event_jLabelAdhInfoMouseEntered

    private void jLabelAdhInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdhInfoMouseExited
        // TODO add your handling code here:
        f.setBorderToJLabel(Color.WHITE, jLabelAdhInfo);
    }//GEN-LAST:event_jLabelAdhInfoMouseExited

    public void AfficherLivreEmp(String stat) {

        ArrayList<Emprunter> list = emprunter.Afficher(stat);
        String[] colones = {"ID Emprunt", "ID Livre", "ID Adherent", "Date Empeunt", "Date Retour", "Statut", "Observation"};

        Object[][] lignes = new Object[list.size()][colones.length];

        for (int i = 0; i < list.size(); i++) {
            lignes[i][0] = list.get(i).getIdEmp();
            lignes[i][1] = list.get(i).getIdLv();
            lignes[i][2] = list.get(i).getIdAdh();
            lignes[i][3] = list.get(i).getRetour();
            lignes[i][4] = list.get(i).getDateE();
            lignes[i][5] = list.get(i).getDateR();
            lignes[i][6] = list.get(i).getObser();
        }

        DefaultTableModel model = new DefaultTableModel(lignes, colones);
        jTableEmpLivres.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetourLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetourLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetourLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetourLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetourLivre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPerdu;
    private javax.swing.JButton jButtonRet;
    private javax.swing.JButton jButtonSupp;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private com.toedter.calendar.JDateChooser jDateChooserDateEmp;
    private com.toedter.calendar.JDateChooser jDateChooserDateRetour;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAdhInfo;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelLvInfo;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAdhID;
    private javax.swing.JSpinner jSpinnerLvID;
    private javax.swing.JTable jTableEmpLivres;
    private javax.swing.JTextArea jTextAreaObser;
    // End of variables declaration//GEN-END:variables
}
